=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/MARCAS/XML/ejers ramdom/EJ2.2.dtd
<!ELEMENT polideportivo (curso+)>
<!ELEMENT curso (horai,duracion,(lunes,martes,miercoles,jueves,viernes,sabado,domingo)+,profesor,alumno*)>
<!ATTLIST curso id ID #REQUIRED>
<!ATTLIST curso nivel (inicial|medio|avanzado) #REQUIRED>
<!ELEMENT horai (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT porfesor EMPTY>
<!ELEMENT alumno (nombre,edad,discapacidad)>
<!ELEMENT nombre EMPTY>
<!ELEMENT edad EMPTY>
<!ELEMENT discapacidad #IMPLIED>

=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/1ºASIR/MARCAS/XML/ejers ramdom/EJ2.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE polideportivo SYSTEM "EJ2.2.dtd">
<polideportivo>
    <curso id="c24" nivel="inicial" >
        <horai>5</horai>
        <duracion>6</duracion>
        <dia></dia>
        <profesor>Pedro</profesor>
        <alumno>
            <nombre>Marco</nombre>
            <edad>19</edad>
            <discapacidad>Si</discapacidad>
        </alumno>
    </curso>
</polideportivo>
