=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/MARCAS/XML/ejers ramdom/nota.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="nota">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="para" type="xs:string" fixed="Pedro"/>
                <xs:element name="de" type="xs:string" />
                <xs:element name="cabecera" type="xs:string">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Trabajo"/>
                            <xs:enumeration value="Amigo"/>
                            <xs:enumeration value="Otros"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="codigo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[a-zA-Z]"/>
                            <!--[a-z]
                                [a-z A-Z]
                                [0-9]
                                [a-z][A-Z][0-9]
                                [a-z][A-Z][0-9]+ que puede generar de 1 digito a mÃ¡s
                                [A-Z]{2}[0-9]+-->
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="mensaje" type="xs:string" />
                <xs:element name="edad" type="xs:integer"/>
                <xs:element name="fecha-nacimiento" type="xs:date"/>
                <xs:element name="fecha-recepcion" type="xs:date"/>
                <xs:element name="hora-recepcion" type="xs:time"/>
                <xs:element name="indicador" type="xs:boolean"/>
                <xs:element name="numero-mensaje" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/MARCAS/XML/ejers ramdom/nota.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<nota xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nota.xsd">
    <codigo>b</codigo>
    <para>Pedro</para>
    <de>Jose</de>
    <cabecera>Recordatorio</cabecera>
    <mensaje>No te olvides de echar la primitiva</mensaje>
    <edad>25</edad>
    <fecha-nacimiento>2003-02-04</fecha-nacimiento>
    <fecha-recepcion>2022-04-30</fecha-recepcion>
    <hora-recepcion>12:13:00</hora-recepcion>
    <indicador>true</indicador>
    <numero-mensaje>4</numero-mensaje>
</nota>
