=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/MARCAS/XML/SCHEMA/nota.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="nota">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="codigo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]+" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="para" type="xs:string" />
                <xs:element name="de" type="xs:string" />
                <xs:element name="cabecera">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="TRABAJO" />
                            <xs:enumeration value="AMIGOS" />
                            <xs:enumeration value="OTROS" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="mensaje" type="xs:string" />
                <xs:element name="edad" type="xs:integer" />
                <xs:element name="fecha-nacimiento" type="xs:date" />
                <xs:element name="fecha-recepcion" type="xs:date" />
                <xs:element name="hora" type="xs:time" />
                <xs:element name="leido" type="xs:boolean" />
                <xs:element name="numero" type="xs:integer" />

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/MARCAS/XML/SCHEMA/nota (1).xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<nota xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="nota.xsd">
<codigo>1</codigo>
<para>Pedro</para>
<de>Jose</de>
<cabecera>AMIGOS</cabecera>
<mensaje>No te olvides de echar la primitiva</mensaje>
<edad>23</edad>
<fecha-nacimiento>1998-01-05</fecha-nacimiento>
<fecha-recepcion>2022-03-30</fecha-recepcion>
<hora>12:24:10</hora>
<leido>false</leido>
<numero>23</numero>
</nota>
