=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/1ºASIR/MARCAS/XML/SCHEMA/personas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:simpleType name="tipoSexo">
    <xs:restriction base="xs:string">
        <xs:pattern value="hombre|mujer"></xs:pattern>
    </xs:restriction>

</xs:simpleType>
<xs:simpleType name="tipoDni">
    <xs:restriction base="xs:string">
        <xs:pattern value="[0-9]{6}[0-9]?[0-9]?[A-Z]"></xs:pattern>
    </xs:restriction>
<!-- kñlkñlk -->
</xs:simpleType>

    <xs:element name="personas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dni" type="tipoDni" />
                            <xs:element name="fnac" type="xs:date" />
                            <xs:element name="telefono">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:positiveInteger">
                                            <xs:attribute name="tipo" use="required" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="edad" type="xs:integer" />
                            <xs:element name="incidencia" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="codigo" type="xs:integer" />
                                        <xs:element name="descripcion" type="xs:string" />
                                        <xs:element name="resuelto">
                                            <xs:complexType>
                                                <xs:attribute name="valor" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="sexo" use="required" type="tipoSexo" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/MARCAS/XML/SCHEMA/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="personas.xsd">
    <persona sexo="hombre">
        <dni>123347A</dni>
        <fnac>2000-02-12</fnac>
        <telefono tipo="fijo">913457837</telefono>
        <edad>21</edad>
        <incidencia>
            <codigo>123</codigo>
            <descripcion>No tiene datos</descripcion>
            <resuelto valor="si"/>
        </incidencia>
        <incidencia>
            <codigo>213</codigo>
            <descripcion>No da tono</descripcion>
            <resuelto valor="no"/>
        </incidencia>
    </persona>
    <persona sexo="mujer">
        <dni>454444B</dni>
        <fnac>1998-12-10</fnac>
        <telefono tipo="mÃ³vil">65456456</telefono>
        <edad>23</edad>
    </persona>
</personas>
