=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/1ºASIR/MARCAS/XML/ejers ramdom/auto.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="auto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="marca">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="citroen"/>
                            <xs:enumeration value="renault"/>
                            <xs:enumeration value="seat"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="modelo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="ibiza"/>
                            <xs:enumeration value="xara"/>
                            <xs:enumeration value="megane"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="kms" type="xs:integer" />
                <xs:element name="consumo100" type="xs:decimal" />
                <xs:element name="fecha_compra" type="xs:date" />
                <xs:element name="aire_acondicionado" type="xs:boolean" />
                <xs:element name="matricula">
                    <xs:simpleType>
                    <xs:restriction base="xs:string">
                    <xs:pattern value="[0-9]{4}[A-Z]{3}"/>
                    </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/1ºASIR/MARCAS/XML/SCHEMA/auto.xml
<?xml version="1.0" encoding="UTF-8"?>
<auto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="auto.xsd">
    <marca>citroen</marca>
    <modelo>xara</modelo>
    <kms>120000</kms>
    <consumo100>5.4</consumo100>
    <fecha_compra>2010-03-29</fecha_compra>
    <aire_acondicionado>true</aire_acondicionado>
    <matricula>1233FDS</matricula>
</auto>
