=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/1ºASIR/MARCAS/XML/ejers ramdom/EJ2.dtd
<!ELEMENT colegio (nombredirector,curso)>
<!ELEMENT nombredirector (#PCDATA)>
<!ELEMENT curso (nivel,tutor,delegado,alumno?,edad?)>
<!ELEMENT nivel (#PCDATA)>
<!ELEMENT tutor (#PCDATA)>
<!ELEMENT delegado (#PCDATA)>
<!ELEMENT alumno (#PCDATA)>
<!ELEMENT edad (#PCDATA)>

=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/1ºASIR/MARCAS/XML/ejers ramdom/EJ2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colegio SYSTEM "EJ2.dtd">
<colegio>
    <nombredirector>Pedro</nombredirector>
    <curso>
        <nivel>Primero</nivel>
        <tutor>Paco</tutor>
        <delegado>David</delegado>
        <alumno>Marco</alumno>
        <edad>13</edad>
    </curso>
</colegio>
