=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/1ºASIR/MARCAS/XML/ejers ramdom/EJ5.dtd
<!ELEMENT pedido (articulo+,fecha,cliente)>
<!ELEMENT articulo (nombre,tipo?,precio,codprod)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo EMPTY>
<!ATTLIST tipo valor (electrico|gasolina) #REQUIRED>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT codprod (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT cliente (comprador,recoger,pago)>
<!ELEMENT comprador (nombre,ciudad,direccion,codpostal)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT codpostal (#PCDATA)>
<!ELEMENT recoger (#PCDATA)>
<!ELEMENT pago (calle,codpostal)>
<!ELEMENT calle (#PCDATA)>

=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/MARCAS/XML/ejers ramdom/EJ5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedido SYSTEM "EJ5.dtd">
<pedido>
    <articulo>
        <nombre>Cortadora de cesped</nombre>
        <tipo valor="electrico"/>
        <precio>148.95</precio>
        <codprod>872-AA</codprod>
    </articulo>
    <articulo>
        <nombre>Podadora</nombre>
        <precio>7.98</precio>
        <codprod>926-FH</codprod>
    </articulo>
    <fecha>20 de octubre del 99</fecha>
    <cliente>
        <comprador>
            <nombre>Roberto Movilla</nombre>
            <ciudad>Albacete</ciudad>
            <direccion>Plaza de la Duquesa 12</direccion>
            <codpostal>05020</codpostal>
        </comprador>
        <recoger>Alicia Abad</recoger>
        <pago>
            <calle>General Ricardos 56, Madrid</calle>
            <codpostal>28055</codpostal>
        </pago>
    </cliente>
</pedido>
