=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/1ºASIR/MARCAS/XML/ejers ramdom/tabla_periodica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tabla_periodica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="estado">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="solido"/>
                            <xs:enumeration value="liquido"/>
                            <xs:enumeration value="gaseoso"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="nombre" type="xs:string" />
                <xs:element name="simbolo">
                    <xs:simpleType>
                    <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z]{1}[a-z]{2}"/>
                    </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="numero_atomico" type="xs:integer" />
                <xs:element name="peso_atomico" type="xs:decimal" />
                <xs:element name="punto_ebulliciÃ³n" type="xs:decimal" />
                <xs:element name="densidad" type="xs:decimal" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/1ºASIR/MARCAS/XML/ejers ramdom/tabla_periodica.xml
<?xml version="1.0" encoding="UTF-8"?>
<tabla_periodica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="tabla_periodica.xsd">
    <estado>solido</estado>
    <nombre>litio</nombre>
    <simbolo>Abc</simbolo>
    <numero_atomico>55</numero_atomico>
    <peso_atomico>55.5</peso_atomico>
    <punto_ebullición>90.5</punto_ebullición>
    <densidad>53.2</densidad>
</tabla_periodica>
