=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/1ºASIR/MARCAS/XML/TODOS LOS EJERS ENRI/XML/ej1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="grupo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string" />
                <xs:element name="disco" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" />
                            <xs:element name="tema" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                            <xs:element name="aÃ±o" minOccurs="0" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/1ºASIR/MARCAS/XML/TODOS LOS EJERS ENRI/XML/ej1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE grupo SYSTEM "ej11.dtd">-->
<grupo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ej1.xsd">
    <nombre>Fito &amp; Fitipaldis</nombre>
    <disco>
        <titulo>Por la boca muere el pez</titulo>
        <tema>Me equivocaría otra vez</tema>
        <tema>Como pollo sin cabeza</tema>
        <tema>Sobra la luz</tema>
        <año>2006</año>
    </disco>
    <disco>
        <titulo>Lo más lejos a tu lado</titulo>
    </disco>
</grupo>
