=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/1ºASIR/MARCAS/XML/TODOS LOS EJERS ENRI/XML/nota1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="nota">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="para" type="xs:string"  fixed="Pedro"/>
                <xs:element name="de" type="xs:string" />
                <xs:element name="cabecera" type="xs:string" />
                <xs:element name="mensaje" type="xs:string" />
                <xs:element name="edad" type="xs:integer"/>
                <xs:element name="fecha_nacimiento" type="xs:date"/>
                <xs:element name="fecha_de_recepcion" type="xs:date"/>
                <xs:element name="hora" type="xs:time"/>
                <xs:element name="indicador" type="xs:boolean"/>
                <xs:element name="nmnesaje" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/1ºASIR/MARCAS/XML/TODOS LOS EJERS ENRI/XML/nota.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<nota xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nota1.xsd">
    <para>Pedro</para>
    <de>Jose</de>
    <cabecera>Recordatorio</cabecera>
    <mensaje>No te olvides de echar la primitiva</mensaje>
    <edad>25</edad>
    <fecha_nacimiento>2003-04-02</fecha_nacimiento>
    <fecha_de_recepcion>2022-04-01</fecha_de_recepcion>
    <hora>13:13:00</hora>
    <indicador>true</indicador>
    <nmnesaje>12</nmnesaje>
</nota>
