=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/MARCAS/XML/TODOS LOS EJERS ENRI/XML/alquiler.dtd
<!ELEMENT alquiler (polideportivo+)>
<!ELEMENT polideportivo (nombre,direccion,precio?,pista*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio hora NMTOKEN #REQUIRED>
<!ELEMENT pista (numero,reserva?)>
<!ATTLIST pista tipo (padel|tenis) #REQUIRED>
<!ATTLIST pista cubierta (si|no) #REQUIRED>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT reserva (fecha,persona)>
<!ATTLIST reserva luz (si|no) #REQUIRED>
<!ELEMENT fecha (#PCDATA)>
<!ATTLIST fecha hora_inicio NMTOKEN #REQUIRED>
<!ATTLIST fecha hora_fin NMTOKEN #REQUIRED>
<!ELEMENT persona (nombre,numsocio?)>
<!ELEMENT numsocio (#PCDATA)>

=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/MARCAS/XML/TODOS LOS EJERS ENRI/XML/alquiler.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alquiler SYSTEM "alquiler.dtd">
<alquiler>
    <polideportivo>
        <nombre>San Chad</nombre>
        <direccion>C/El mazas,69</direccion>
        <precio hora="12:00">22€</precio>

        <pista tipo="padel" cubierta="si">
            <numero>12</numero>
        </pista>


        <pista tipo="tenis" cubierta="no">
            <numero>8</numero>
            <reserva luz="si">
                <fecha hora_inicio="13:00" hora_fin="15:00">12/3/2021</fecha>
                <persona>
                    <nombre>Manuel Avova</nombre>
                    <numsocio>7690</numsocio>
                </persona>
            </reserva>
        </pista>

        

    </polideportivo>

    <polideportivo>
        <nombre>Coto del Duque</nombre>
        <direccion>C/Blanca,42</direccion>
        <precio hora="9:00">18€</precio>

        <pista tipo="padel" cubierta="no">
            <numero>7</numero>
        </pista>


        <pista tipo="tenis" cubierta="si">
            <numero>2</numero>
        </pista>

    </polideportivo>

</alquiler>
