=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/MARCAS/XML/TODOS LOS EJERS ENRI/XML/alumnos.dtd
<!ELEMENT polideportivo (curso_natacion*)>
<!ELEMENT curso_natacion (hora_inicio,duracion,dias+,profesor,alumno*)>
<!ATTLIST curso_natacion identificador ID #REQUIRED>
<!ATTLIST curso_natacion nivel (inicial|medio|avanzado) #REQUIRED>
<!ELEMENT hora_inicio (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT dias EMPTY>
<!ATTLIST dias valor (lunes|martes|miercoles|jueves|viernes|sabado|domingo) #REQUIRED>
<!ELEMENT profesor (#PCDATA)>
<!ELEMENT alumno (nombre,edad)>
<!ATTLIST alumno discapacidad NMTOKEN #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>

=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/1ºASIR/MARCAS/XML/TODOS LOS EJERS ENRI/XML/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE polideportivo SYSTEM "alumnos.dtd">
<polideportivo>

    <curso_natacion identificador="C128" nivel="inicial">

        <hora_inicio>12:00</hora_inicio>
        <duracion>1</duracion>
        <dias valor="lunes"></dias>
        <profesor>Miguel Pijala</profesor>

        <alumno discapacidad="si">
            <nombre>Antonio Marmitaco</nombre>
            <edad>12</edad>
        </alumno>

        <alumno discapacidad="si">
            <nombre>Pedro Picoletos</nombre>
            <edad>14</edad>
        </alumno>

    </curso_natacion>

    <curso_natacion identificador="B096" nivel="medio">

        <hora_inicio>20:00</hora_inicio>
        <duracion>2</duracion>
        <dias valor="martes"></dias>
        <profesor>Rodrigo Monte</profesor>

        <alumno discapacidad="no">
            <nombre>Jorge Lalo</nombre>
            <edad>18</edad>
        </alumno>

        <alumno discapacidad="no">
            <nombre>Jose Gonzo</nombre>
            <edad>16</edad>
        </alumno>

    </curso_natacion>

</polideportivo>
