<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE libro-direcciones[
<!ELEMENT libro-direcciones (entrada)+>
<!ELEMENT entrada (nombre,direccion*,tel*,email*,comentarios?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (calle,codigo-postal,localidad,pais)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT codigo-postal (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ATTLIST tel principal (si|no) "no">
<!ELEMENT fax (#PCDATA)>
<!ELEMENT email EMPTY>
<!ATTLIST email href CDATA #REQUIRED>
<!ELEMENT comentarios (#PCDATA)>
]>

<libro-direcciones>
	<entrada>
		<nombre>Florentina</nombre>
		<direccion>
			<calle>San Benito 6</calle>
			<codigo-postal>28029</codigo-postal>
			<localidad>Madrid</localidad>
			<pais>España</pais>
		</direccion>
		<tel principal="si">623-27-03-71</tel>
		<tel>656-23-44-33</tel>
		<email href="mailto:pepe@gmail.com"/>
	</entrada>
	<entrada>
		<nombre>Carlos Tena</nombre>
		<tel>513-34-65-35</tel>
		<email href="mailto:cate@gmail.com"/>
		<comentarios>Nunca dejar mensajes en su contestador</comentarios>
	</entrada>
</libro-direcciones>