=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/MARCAS/XML/TODOS LOS EJERS ENRI/XML/dtd-direcciones.dtd
<!ELEMENT libro-direcciones (entrada)+>
<!ELEMENT entrada (nombre,direccion*,tel*,email*,comentarios?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (calle,codigo-postal,localidad,pais)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT codigo-postal (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ATTLIST tel principal (si|no) "no">
<!ELEMENT fax (#PCDATA)>
<!ELEMENT email EMPTY>
<!ATTLIST email href CDATA #REQUIRED>
<!ELEMENT comentarios (#PCDATA)>

=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/MARCAS/XML/TODOS LOS EJERS ENRI/XML/direcciones.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE libro-direcciones SYSTEM "dtd-direcciones.dtd">
<libro-direcciones>
  <entrada>
    <nombre>Juan Sanz</nombre>
    <direccion>
      <calle>San Benito 6</calle>
      <codigo-postal>28029</codigo-postal>
      <localidad>Madrid</localidad>
      <pais>Espaï¿½a</pais>
    </direccion>
    <tel principal="si">623-27-03-71</tel>
    <tel>656-23-44-33</tel>
    <email href="mailto:pepe@gmail.com"/>
	</entrada>
	<entrada>
		<nombre>Carlos Tena</nombre>
		<tel>513-34-65-35</tel>
		<email href="mailto:cate@gmail.com"/>
    <comentarios>Nunca dejar mensajes en su contestador</comentarios>
  </entrada>
</libro-direcciones>
