=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/MARCAS/XML/TODOS LOS EJERS ENRI/XML/ej2.dtd
<!ELEMENT colegio (nomdir,cursos)>
<!ELEMENT nomdir (#PCDATA)>
<!ELEMENT cursos (nivel,nomtut,nomdel,nomalu?,edad?)>
<!ELEMENT nivel (#PCDATA)>
<!ELEMENT nomtut (#PCDATA)>
<!ELEMENT nomdel (#PCDATA)>
<!ELEMENT nomalu (#PCDATA)>
<!ELEMENT edad (#PCDATA)>

=== marcobatistacalado/CFGS-Administraci-n-Sistemas-Inform-ticos-En-Red/MARCAS/XML/TODOS LOS EJERS ENRI/XML/ej2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE colegio SYSTEM "ej2.dtd">-->
<colegio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ej2.xsd">
    <nomdir>Antonio Calado</nomdir>
    <cursos>
        <nivel>1</nivel>
        <nomtut>Juan Pérez</nomtut>
        <nomdel>Iñigo Momoa</nomdel>
        <nomalu>Jorge Nitales</nomalu>
        <edad>5</edad>
    </cursos>
</colegio>
